### ISSUE TITLE
I can't  put the  bot  to just to run my commands

### ISSUE THREAD

**Issue by ghost** [Fytex/H43#6]
the bot does not recognize my discord account when i try to run the program it says that the commands are available to everyone on the server could you help me, thank you have a nice day :)

**Comment by Fytex** [comment]
Hi,

Next to the file you are executing there is a file called `config.ini`. Inside it, you can add a new line under `[Users]` with your name followed by your discord ID. Then name doesn't really matters, it just works as a label.

You have two examples there which are preceded by a `#` which is a comment. So you must put your line without `#`.

If you don't know how to get your Discord User ID, search on the web :)

Finally, be sure you are running your executable next to the `config.ini` file.

Example:
```
[Users]
#User=123456789012345678 (ID)  -> Don't use '#'
#Fytex=321346463148015626
criaK=00000000000000000
````

Have a nice day :)
